### Numpy :

* Installing numpy library
* importing numpy library
* creation of arrays in different dimensions.
* Accessing of the array elements.
* Looping of arrays.
* Shaping and reshaping of arrays

### Installing numpy library:

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


### Importing numpy Library:

In [2]:
import numpy as np

### Creating arrays in different dimensions::

### 1-d array:

* 1-d array is as same as a list.


In [3]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [5]:
a.dtype  ### datatype of the elements in the array.

dtype('int32')

In [8]:
type(a)  ### variable type

numpy.ndarray

In [9]:
a = np.array([1,'a',3,'b'])
a

array(['1', 'a', '3', 'b'], dtype='<U11')

In [10]:
a.dtype

dtype('<U11')

In [11]:
a = np.array([1,2,1+2j])

In [12]:
a

array([1.+0.j, 2.+0.j, 1.+2.j])

In [13]:
a.dtype

dtype('complex128')

In [14]:
### task : create an array suing all the datatypes available in the arrays

In [15]:
a

array([1.+0.j, 2.+0.j, 1.+2.j])

In [16]:
a = np.append(a,'a')  ## adding a single element

In [17]:
a

array(['(1+0j)', '(2+0j)', '(1+2j)', 'a'], dtype='<U64')

In [18]:
a = np.append(a,['b',1,2])   ### adding multiple elements 

In [19]:
a

array(['(1+0j)', '(2+0j)', '(1+2j)', 'a', 'b', '1', '2'], dtype='<U64')

In [20]:
a = np.arange(1,11)   ### creating array using a range keyword
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
a = np.arange(2,11,2) ### start,end,step value

a

array([ 2,  4,  6,  8, 10])

In [24]:
a = np.arange(1,11,2)
a

array([1, 3, 5, 7, 9])

In [26]:
a.nbytes  ## total memeory space array occupied

20

In [28]:
a.itemsize ### each element size

4

In [30]:
len(a)   ### number of elements in the array

5

In [32]:
### linear spacing:

a = np.linspace(1,10,20) ## creating array with required number of elements within the range 
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [33]:
### logarithmic spacing:

a = np.logspace(1,10,20)
a

array([1.00000000e+01, 2.97635144e+01, 8.85866790e+01, 2.63665090e+02,
       7.84759970e+02, 2.33572147e+03, 6.95192796e+03, 2.06913808e+04,
       6.15848211e+04, 1.83298071e+05, 5.45559478e+05, 1.62377674e+06,
       4.83293024e+06, 1.43844989e+07, 4.28133240e+07, 1.27427499e+08,
       3.79269019e+08, 1.12883789e+09, 3.35981829e+09, 1.00000000e+10])

In [34]:
arr=np.array([1, 2, '3',[4, 5, 6], 'hello'])
arr

array([1, 2, '3', list([4, 5, 6]), 'hello'], dtype=object)

In [35]:
len(arr)

5

In [36]:
arr.itemsize

8

In [38]:
arr.nbytes

40

In [39]:
np.full(10,"python")  ### repeating a particular element withn required number of times 

array(['python', 'python', 'python', 'python', 'python', 'python',
       'python', 'python', 'python', 'python'], dtype='<U6')

In [40]:
np.full(5,2)

array([2, 2, 2, 2, 2])

In [41]:
np.ones(10)  ### repating 1's required number of times

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [42]:
np.ones(10,dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [46]:
np.zeros(10,dtype = int)  ### repeating zeroes required number of times

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [48]:
a.ndim   ### checking the dimension of the array

1

### 2-d array

* combination of more 1-d arrays.

In [49]:
b = np.array([[1,2,3,4],[5,6,7,8]])

In [50]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [51]:
b.ndim

2

In [52]:
b.nbytes

32

In [53]:
b.itemsize

4

In [54]:
len(b)  ### numbers of rows

2

In [55]:
b.shape  ### number of rows and columns

(2, 4)

In [56]:
b.size  ### total elements in the array

8

### 3-d array:

* combination of more 2-d arrays 

In [58]:
c = np.array([[[1,2,3,4],[5,6,7,8]],[[10,11,2,3],[13,1,2,3]]])
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[10, 11,  2,  3],
        [13,  1,  2,  3]]])

In [59]:
c.ndim

3

In [61]:
c.itemsize

4

In [62]:
c.nbytes

64

In [64]:
c.shape  ### 2-d arrays,rows,columns

(2, 2, 4)

### Mutli dimensional array:

In [70]:
d = np.array([[1,2,3,4,5],[6,7,8,9,10]],ndmin = 20)
d

array([[[[[[[[[[[[[[[[[[[[ 1,  2,  3,  4,  5],
                         [ 6,  7,  8,  9, 10]]]]]]]]]]]]]]]]]]]])

In [71]:
d.ndim

20

In [67]:
d = np.array([1,2,3,4,5],ndmin = 2)
d

array([[1, 2, 3, 4, 5]])

In [72]:
d.shape

(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 5)

### Accessing the elements from the array:

#### 1-d array:

In [75]:
a = np.arange(10,21)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [76]:
a[0]

10

In [77]:
a[-1]

20

In [78]:
a[:3]

array([10, 11, 12])

In [79]:
a[-3:]

array([18, 19, 20])

In [80]:
a[::2]

array([10, 12, 14, 16, 18, 20])

In [81]:
a[1::2]

array([11, 13, 15, 17, 19])

In [82]:
a[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

#### 2-d array:

In [89]:
b = np.array([[1,2,3,5],[6,7,9,0]])
b

array([[1, 2, 3, 5],
       [6, 7, 9, 0]])

In [85]:
b[0]

array([1, 2, 3, 5])

In [86]:
b[-1]

array([6, 7, 9, 0])

In [88]:
b[0,1]   ### row_index,element index

2

In [90]:
b[-1,-1]

0

In [91]:
b[0:2,-1]

array([5, 0])

In [92]:
b[:,-2:]

array([[3, 5],
       [9, 0]])

#### 3-d array:

In [93]:
c = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,2,5],[5,10,12,5]]])
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10,  2,  5],
        [ 5, 10, 12,  5]]])

In [94]:
c[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [95]:
c[1]

array([[ 9, 10,  2,  5],
       [ 5, 10, 12,  5]])

In [96]:
c[0,0]

array([1, 2, 3, 4])

In [97]:
c[1,1]

array([ 5, 10, 12,  5])

In [98]:
c[0,1,-1]

8

In [99]:
c[0,:,-1]

array([4, 8])

In [100]:
c[:,:,-1]

array([[4, 8],
       [5, 5]])

In [101]:
c[:,:,-2:]

array([[[ 3,  4],
        [ 7,  8]],

       [[ 2,  5],
        [12,  5]]])

In [102]:
c[0,:,1]

array([2, 6])