### Numpy Continuation:

### Shaping and Reshaping of arrays:

#### Shaping:

* rows and columns

In [3]:
import numpy as np
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
a.shape

(5,)

In [9]:
b = np.array([[1,2,3,4,5],[6,7,8,9,0]])
b

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [7]:
b.shape

(2, 5)

In [10]:
c = np.array([[[1,2,3,4,5],[6,7,8,9,0]],[[4,5,7,7,8],[9,8,7,6,5]]])
c

array([[[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 0]],

       [[4, 5, 7, 7, 8],
        [9, 8, 7, 6, 5]]])

In [11]:
c.shape

(2, 2, 5)

#### Reshaping:

* Giving a new shape to an array.
* the product of rows and columns in the new array should be equal to total number of elements

In [17]:
a = np.append(a,6)

In [13]:
### 1-d array into 2-d array:

a.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [16]:
a.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [18]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
b = a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
a.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [21]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [23]:
### 1-d array to 3-d array:

a

array([1, 2, 3, 4, 5, 6])

In [24]:
b

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [25]:
a.reshape(2,3,1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [26]:
a.reshape(3,2,1)

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

In [27]:
a.reshape(1,3,2)

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [28]:
a.reshape(2,3,1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [29]:
a.reshape(1,6,1)

array([[[1],
        [2],
        [3],
        [4],
        [5],
        [6]]])

In [30]:
a

array([1, 2, 3, 4, 5, 6])

In [32]:
a.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
a.reshape(-1,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
a.reshape(-1,3,2)

array([[[1, 2],
        [3, 4],
        [5, 6]]])

### Iteration of array elements:

#### 1-d array:

In [41]:
a

array([1, 2, 3, 4, 5, 6])

In [42]:
for i in a:
    print(i,end = " ")

1 2 3 4 5 6 

In [43]:
b

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [47]:
for i in b:   ### i holds each row
    for j in i:  ### j holds each row elements
        print(j,end = " ")
    

1 2 3 4 5 6 7 8 9 0 

In [48]:
c

array([[[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 0]],

       [[4, 5, 7, 7, 8],
        [9, 8, 7, 6, 5]]])

In [50]:
for i in c:  ###  i holds each 2-d array
    for j in i: ### j holds each row
        for k in j: ### k holds each row element
            print(k,end = " ")
    

1 2 3 4 5 6 7 8 9 0 4 5 7 7 8 9 8 7 6 5 

In [51]:
### keyword for iterating the array elements:

for i in np.nditer(c):
    print(i,end = " ")

1 2 3 4 5 6 7 8 9 0 4 5 7 7 8 9 8 7 6 5 

In [53]:
for i in np.nditer(b):
    print(i,end = " ")

1 2 3 4 5 6 7 8 9 0 

### Joining of arrays:

In [63]:
### 1-d array:

a = np.arange(1,10)
b = np.arange(21,30)
c = np.concatenate((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 21, 22, 23, 24, 25, 26, 27, 28,
       29])

In [65]:
### 2-d array:

c = a.reshape(3,3)
d = b.reshape(3,3)

e = np.concatenate((c,d))
e

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [67]:
### 3-d array

c = a.reshape(3,3,1)
d = b.reshape(3,3,1)
e = np.concatenate((c,d))
e

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[21],
        [22],
        [23]],

       [[24],
        [25],
        [26]],

       [[27],
        [28],
        [29]]])

### Stastical and mathematical operations of arrays:

In [72]:
a = a.reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
np.min(a) ### minimum value in the array

1

In [74]:
np.max(a)  ###maximum value in the array

9

In [75]:
np.argmin(a)  ### index of minimum value in the array

0

In [78]:
np.argmax(a)  ### index of maximum value in the array

8

In [80]:
a.mean()  ### mean of the array elements

5.0

In [81]:
a.sum()   ### sum of all the array elements

45

In [84]:
np.average(a)   ### average of all array elements

5.0

In [85]:
np.var(a) ### variance of the array elements

6.666666666666667

In [88]:
np.median(a)  ### median of the array elements

5.0

In [89]:
np.std(a) ###  standard deviation of the array elements

2.581988897471611

In [90]:
np.min(a,1)   ### minimum values row wise
   ### 1 represents row
   ### 0 represents column

array([1, 4, 7])

In [91]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
np.min(a,0)

array([1, 2, 3])

In [93]:
np.max(a,0)

array([7, 8, 9])

In [94]:
np.max(a,1)

array([3, 6, 9])

In [95]:
np.var(a,1)

array([0.66666667, 0.66666667, 0.66666667])

In [96]:
np.std(a,0)

array([2.44948974, 2.44948974, 2.44948974])

In [97]:
np.argmin(a,1)

array([0, 0, 0], dtype=int64)

In [98]:
np.argmax(a,0)

array([2, 2, 2], dtype=int64)

In [99]:
np.sum(a,1)

array([ 6, 15, 24])

In [100]:
np.sum(a,0)

array([12, 15, 18])

#### Stacking:

* organising/arranging in an proper order
    * vertical stacking
    * Hortizantal stacking


In [109]:
### horizantal stacking:

a
b = a
np.hstack(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
np.hstack((a,b))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [105]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [107]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
np.sqrt(a)   ### squares of the array element

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [113]:
np.exp(a)  ## exponenetial value of each array element

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [115]:
np.sin(a)   ### sine values of array elements

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [119]:
np.cos(a) ### cosine values of array elements

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

In [121]:
np.tan(a)  ### tan values of array elements

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [123]:
np.log(a)   ### log values of array elements

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [125]:
np.log2(a)  ### log values of array elements with base 2

array([[0.        , 1.        , 1.5849625 ],
       [2.        , 2.32192809, 2.5849625 ],
       [2.80735492, 3.        , 3.169925  ]])

In [127]:
np.log10(a)  ### log values of array elements with base 10

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [128]:
np.remainder(a,2)  

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]], dtype=int32)

In [129]:
np.degrees(a)

array([[ 57.29577951, 114.59155903, 171.88733854],
       [229.18311805, 286.47889757, 343.77467708],
       [401.07045659, 458.3662361 , 515.66201562]])

In [130]:
np.diff(a)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [132]:
np.ediff1d(a)  ## converts array into 1-d array and finds the difference

array([1, 1, 1, 1, 1, 1, 1, 1])

In [134]:
np.i0(a)    ### bessel function

array([[   1,    2,    4],
       [  11,   27,   67],
       [ 168,  427, 1093]])

In [135]:
np.mod(a,4)

array([[1, 2, 3],
       [0, 1, 2],
       [3, 0, 1]], dtype=int32)

In [136]:
np.power(a,4)

array([[   1,   16,   81],
       [ 256,  625, 1296],
       [2401, 4096, 6561]], dtype=int32)

In [138]:
np.reciprocal(a,dtype = float)

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667],
       [0.14285714, 0.125     , 0.11111111]])

In [139]:
np.multiply(a,3)

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [140]:
np.divide(a,2)

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [142]:
a = np.array([1+2j,2+3j,4+5j])
a

array([1.+2.j, 2.+3.j, 4.+5.j])

In [143]:
np.real(a)

array([1., 2., 4.])

In [144]:
np.imag(a)

array([2., 3., 5.])

### Ravel and Flatten:


* Ravel: when we create a copy of original array using ravel and make changes in the copy array,those changes will be applied to the original array also.
* Flatten : when we create a copy of original array using ravel and make changes in the copy array,those changes will not apply to the original array .

In [154]:
original = np.array([1,2,3,4])
original   ### original array

array([1, 2, 3, 4])

In [155]:
copyrav = original.ravel()
copyrav   ### copy array

array([1, 2, 3, 4])

In [156]:
copyrav[0] = 2

In [157]:
copyrav

array([2, 2, 3, 4])

In [158]:
original

array([2, 2, 3, 4])

In [159]:
original

array([2, 2, 3, 4])

In [160]:
copyflat = original.flatten()
copyflat

array([2, 2, 3, 4])

In [161]:
copyflat[0] = 1

In [162]:
copyflat

array([1, 2, 3, 4])

In [163]:
original

array([2, 2, 3, 4])

### Random methods:

In [176]:
np.random.randint(100)   ### integer value within the given range
 

83

In [182]:
np.random.rand()  ## float value within 0 and 1 range.

0.7579442343531111

In [192]:
np.random.randint(200,size = (20))  ### generates defined number of random integer values within the given range,

array([101, 199,  80, 158,  45,  14, 147,  64,  37,  85,  75, 197,  30,
        64,  40,   3, 147, 104, 192, 176])

In [193]:
np.random.randint(100,size = (2,4))

array([[20, 70, 76, 70],
       [57, 56, 31, 79]])

In [200]:
np.random.randint(100,200,size = (2,2,4))

array([[[136, 148, 122, 183],
        [199, 179, 143, 100]],

       [[154, 184, 158, 171],
        [199, 184, 187, 166]]])

In [212]:
np.random.choice([1,2,3,4,6,7])

3

In [218]:
np.random.choice([1,2,3,4,5,6],size = (2,2))

array([[3, 5],
       [6, 4]])

In [220]:
np.random.choice([1,2,3,4,5,6],size = (3,2,2))

array([[[5, 1],
        [4, 4]],

       [[1, 3],
        [3, 3]],

       [[5, 1],
        [5, 5]]])

In [229]:
np.random.choice([1,2,3,4,6],p = [0.5,0.1,0.1,0.2,0.1])

1

In [236]:
np.random.choice([1,2,3,4,6],p = [0.5,0.1,0.1,0.2,0.1],size = (2,2))

array([[1, 1],
       [3, 1]])

In [239]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [245]:
np.random.shuffle(a)

In [246]:
a

array([3, 1, 6, 5, 2, 4])

In [247]:
np.random.randn(10)

array([-0.65884052,  0.16326004, -0.42510543, -0.22877383,  0.03862169,
       -0.21918123, -0.4127949 ,  0.10715885, -0.57468007, -0.84759198])

In [249]:
np.random.normal()

0.9216394333630651

In [254]:
np.random.binomial(10,p=[0.1],size = (3,2))

array([[1, 0],
       [1, 0],
       [1, 1]])

### Array Filtering:

In [255]:
a = np.array([1,23,5,6,78,90])
b = [True,False,False,True,True,False]
c = a[b]
c

array([ 1,  6, 78])

In [257]:
### print the values which are greater than 10

b = []
for i in a:
    if i >10:
        b.append(True)
    else:
        b.append(False)
        
c = a[b]

In [258]:
c

array([23, 78, 90])

In [260]:
d = a>10
d

array([False,  True, False, False,  True,  True])

In [261]:
c = a[d]

In [262]:
c

array([23, 78, 90])

In [263]:
a = np.array([1,2,3,5])
b = np.array([4,5,6,8])
np.dot(a,b)

72

In [268]:
a.T

array([1, 2, 3, 5])

In [269]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [271]:
a.T  ### transpose

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])